# Generated by Django 4.2.28 on 2026-02-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_make_otpcode_managed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='otp_codes_phone_582405_idx',
            old_name='otp_phone_is_used_idx',
        ),
    ]
